# Generated by Django 5.0.6 on 2024-07-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='dest',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
