# Generated by Django 5.0.6 on 2024-07-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_signup_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='dest',
            field=models.CharField(choices=[('dest 1', 'Option 1'), ('dest 2', 'Option 2'), ('dest 3', 'Option 3')], max_length=50),
        ),
    ]
