# Generated by Django 5.0.6 on 2024-07-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_alter_signup_dest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='dest',
        ),
    ]
