# Generated by Django 5.0.6 on 2024-07-03 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_booking_destination_booking_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='depart_date',
            field=models.DateField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='return_date',
            field=models.DateField(default='None', max_length=10),
        ),
    ]
