# Generated by Django 5.0.6 on 2024-07-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_alter_booking_depart_date_alter_booking_return_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookingmodel',
        ),
        migrations.RenameModel(
            old_name='SignUp',
            new_name='SignUpmodel',
        ),
    ]
