# Generated by Django 5.0.6 on 2024-07-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0009_rename_depart_date_bookingmodel_departdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='destination',
            field=models.CharField(choices=[('', 'Destination'), ('Destination1', 'Goa'), ('Destination2', 'Mumbai'), ('Destination3', 'Laddakh')], default='Destination', max_length=15),
        ),
    ]
