# Generated by Django 5.0.6 on 2024-07-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0010_alter_bookingmodel_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='departDate',
            field=models.DateField(default='00-00-0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='duration',
            field=models.CharField(choices=[('', 'Duration'), ('Duration1', 'month 1'), ('Duration2', 'month 2'), ('Duration3', 'month 3')], default='Duration', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='returnDate',
            field=models.DateField(default='00-00-0000', max_length=10),
        ),
    ]
