# Generated by Django 5.0.6 on 2024-07-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0012_alter_bookingmodel_departdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='departDate',
            field=models.DateField(default='00-00-0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='returnDate',
            field=models.DateField(default='00-00-0000', max_length=10),
        ),
    ]
