# Generated by Django 5.0.6 on 2024-07-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0013_alter_bookingmodel_departdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='destination',
            field=models.CharField(choices=[('', 'Destination'), ('Destination1', 'Goa'), ('Destination2', 'Mumbai'), ('Destination3', 'Laddakh')], max_length=15),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='duration',
            field=models.CharField(choices=[('', 'Duration'), ('Duration1', 'month 1'), ('Duration2', 'month 2'), ('Duration3', 'month 3')], max_length=20),
        ),
    ]
