# Generated by Django 5.0.6 on 2024-07-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0016_alter_bookingmodel_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='destination',
            field=models.CharField(choices=[('Destination', 'Destination'), ('Destination1', 'Goa'), ('Destination2', 'Mumbai'), ('Destination3', 'Laddakh')], default='Destination', max_length=15),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='duration',
            field=models.CharField(choices=[('Duration', 'Duration'), ('month 1', 'Duration1'), ('Duration2', 'month 2'), ('Duration3', 'month 3')], default='Duration', max_length=20),
        ),
    ]
