# Generated by Django 5.0.6 on 2024-07-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0017_alter_bookingmodel_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='duration',
            field=models.CharField(choices=[('Duration', 'Duration'), ('Duration1', 'month 1'), ('Duration2', 'month 2'), ('Duration3', 'month 3')], default='Duration', max_length=20),
        ),
    ]
