# Generated by Django 5.0.6 on 2024-07-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0018_alter_bookingmodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='destination',
            field=models.CharField(choices=[('Destination', 'Destination'), ('Destination1', 'Goa'), ('Destination2', 'Mumbai'), ('Destination3', 'Laddakh')], default='Destination', max_length=15),
        ),
    ]
